 drop table if exists "buyers" cascade;
 drop table if exists "sales" cascade;
 drop table if exists "sold" cascade;
 drop table if exists "finished_materials" cascade;
 drop table if exists "manufacturing" cascade;
 drop table if exists "elements" cascade;
 drop table if exists "raw_materials" cascade;
 drop table if exists "orders" cascade;
 drop table if exists "suppliers" cascade;
